language: objective-c
install: true
env:
  - BUILD_TYPE=mac
  - BUILD_TYPE=win
before_install: bash ./scripts/install.$BUILD_TYPE.script.sh
deploy:
  provider: releases
  api_key:
    secure: O+1H7MYM6x1ir7/BwIqLg8hj1wFCS5xaon81cRp1Mj079+CYk8kpP7mdwShzokyBPSmFmLh/ItBH6PDAkwZ9678DTG8SkovAH9sx8uJ22cUD7HZs+CD0NknlKfZ+N/UZQVlitOwPzSNG/JwyqECU8DqNI4vcW3v95VrAXn1Qzx0=
  file:
    - "./build/gideros.exe"
    - "./build/gideros.dmg"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
